services:
    olympus_platform:
      image: code4anuj/olympus_echo_backend:latest
      container_name: platform
      ports:
        - "5050:5050"
      extra_hosts:
        - "host.docker.internal:host-gateway"


      environment:
        LOKI_ENABLED: "true"
        GRAFANA_LOKI_URL: "https://logs-prod-036.grafana.net/loki/api/v1/push"
        GRAFANA_LOKI_USER_ID: "1220258"
        GRAFANA_LOKI_PASSWORD: ${GRAFANA_API_KEY}
      volumes:
        - ./config.json:/usr/src/app/config.json

